apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: roboshop   # lowercase 'namespace'
  labels:
    app: debug
    project: roboshop   # lowercase 'project' is fine under labels
spec:
  containers:
  - name: debug
    image: joindevops/debug:v1
    command: ["sleep", "3600"]
