apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
    project: roboshop
    purpose: dp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb       # must match the pod template labels
      project: roboshop
      purpose: dp-demo
  template:
    metadata:
      labels:
        app: mongodb     # must match the selector above
        project: roboshop
        purpose: dp-demo
    spec:
      containers:
      - name: mongodb
        image: mongo:6
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
    project: roboshop
    purpose: dp-demo
spec:
  selector:
    app: mongodb       # matches the pod labels
    project: roboshop
    purpose: dp-demo
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
