apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx        # <-- must match pod template
      project: roboshop
      purpose: dp-demo
  template:
    metadata:
      labels:
        app: nginx
        project: roboshop
        purpose: dp-demo
    spec:
      containers:
      - name: mongodb
        image: mongo:6
        ports:
        - containerPort: 27017
