apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop

  labels:
    project: roboshop
    component: mongodb
    tier: db

spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      purpose: dp-demo
      app: roboshop

  template:
    metadata:
      labels:
        purpose: dp-demo
        project: roboshop
        app: nginx
    spec:
      containers:
        - name: nginx
          image: joindevops/mongodb:v1